version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql-test
    command: --lower_case_table_names=1
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=subway
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Seoul
